name = "angellst58 blog"
license = "MIT"
licenselink = "https://github.com/hugo-sid/hugo-blog-awesome/blob/main/LICENSE"
description = "angellst58 blog"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/hugo-sid/hugo-blog-awesome/"

# If you have a running demo of the theme.
#demosite = "https://hugo-blog-awesome.netlify.app/"

tags = ["blog", "responsive", "minimal", "dark", "light"]
features = ["blog", "sass", "dark"]

min_version = "0.87.0"

# If the theme has a single author
[author]
    name = "angellst58"
    homepage = "https://angellst58.me"